name: myportfolio
description: Elia Marcantognini's portfolio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  url_launcher: ^5.4.0
  clipboard_manager: ^0.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/works/
  fonts:
    - family: GoogleSansRegular
      fonts:
      - asset: assets/GoogleSansRegular.ttf