name: myportfolio
description: Elia Marcantognini's portfolio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.0.20

  # cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/works/
  fonts:
    - family: GoogleSansRegular
      fonts:
      - asset: assets/fonts/GoogleSansRegular.ttf